# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (r ${{ matrix.r }}, java ${{ matrix.java }})

    strategy:
      fail-fast: false
      matrix:
        # os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
        # r: ['devel', 'release', 'oldrel-1', '4.2.1', '4.1.1', '4.1.3', '3.6.1']
        # java: [ '8', '11', '13', '17' ]
        os: [ 'macOS-latest' ]
        r: [ 'devel' ]
        java: [ '8' ]
        # include:
          # - http-user-agent: 'release'
            # r: 'devel'
        # config:
          # - {os: macOS-latest,   r: 'release'}
          # - {os: windows-latest, r: 'release'}
          # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          # - {os: ubuntu-latest,   r: 'release'}
          # - {os: ubuntu-latest,   r: 'oldrel-1'}
          # - {os: ubuntu-latest,   r: '3.6.1'}
          # - {os: ubuntu-latest,   r: '4.1.3'}
          # - {os: ubuntu-latest,   r: '4.1.1'}
          # - {os: ubuntu-latest,   r: '4.2.1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
            
      - name: Setup java (x64)
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64
        
      - name: Setup java (x86)
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x86
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: ${{ matrix.http-user-agent }}
          use-public-rspm: true

      - name: "[Stage] [macOS] Install libgit2"
        if: runner.os == 'macOS'
        run: brew install libgit2

      - name: "[Stage] [macOS] Install system libs for pkgdown"
        if: runner.os == 'macOS' && matrix.config.pkgdown != ''
        run: brew install harfbuzz fribidi

      - name: Build site
        run: install.packages(c("systemfonts", "textshaping"))
        shell: Rscript {0}
        
      - name: Build site
        run: install.packages("systemfonts")
        shell: Rscript {0}
        if: ${{ matrix.os == 'macOS-latest' && matrix.r == '3.6.1' }}


      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        if: ${{ matrix.os != 'macOS-latest' }}
        with:
          extra-packages: any::rcmdcheck, XML
      
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        if: ${{ matrix.os == 'macOS-latest' }}
        with:
          packages: knitr, kableExtra, rmarkdown
          extra-packages: any::rcmdcheck, XML, textshaping
        
      - uses: r-lib/actions/setup-tinytex@v2
        
      - uses: r-lib/actions/check-r-package@v2
